### PR TITLE
Use mimic instead of pico2wave.

### LINKED ISSUE #42: TTS doesn't work with other languages than en_US
And frankly, Harry Potter fanfiction should be read in `en_GB` ;).

Also, would it be possible to switch to [mimic](https://mimic.mycroft.ai/). It is free (contrary to svox, which cannot go into most Linux distributions) and it has stdin-to-speech function, so no need to fiddle with temporary files. Difference in the pronunciation is minimal.

### PR DESCRIPTION
**Pull request by mcepl**
Unfortunately, the language setting is gone again.

Fixes #42

### CODE REVIEW

**Comment by wustho** [comment]
Hey there, just read this PR, looks good... But need to test it on my machine first... Thanks

**Comment by mcepl** [comment]
Thinking about this, I wonder whether we shouldn’t use [speechd](https://freebsoft.org/speechd) instead: it is back-end independent and Firefox uses it on Linux, so it should be sufficiently widespread. `spd-say` is the command, and `spd-say -e` can read text from stdin as well.

**Comment by wustho** [comment]
Hey there, @mcepl , sure but hold up a bit... I kinda have some thoughts about tts engine, I will merge this first (after testing), and put my thoughts and will ping you later to discuss the engine...

**Comment by wustho** [comment]
@mcepl Hello there, I just add `SpeakerBaseModel` if developers are interested in adding their fav tts engine, you can check the example of how to use it in https://github.com/wustho/epy/blob/master/epy.py#L107

Cheers!

**Comment by mcepl** [comment]
That looks really great! I guess the configuration is `PreferredTTSEngine` with value from `cmd` class attribute?

**Comment by wustho** [comment]
> I guess the configuration is PreferredTTSEngine with value from cmd class attribute?

Yes, it is!

> Oh! Does it do auto-discovery? Great!

It should, but need to define `available` attribute, because some tts engine like `pico2wave` needs dependency like `play`.

**Pull request merged**
